### ISSUE TITLE
TypeError: channel.assertQueue(...).then(...).catch is not a function

### ISSUE THREAD

**Issue by pnedelko** [tjmehta/amqplib-rpc#6]
Unfortunately, doesn't work with `amqplib@0.1.3`, because of old `when` library

```
TypeError: channel.assertQueue(...).then(...).catch is not a function
    at /Users/pnedelko/projects/elastic/api/node_modules/amqplib-rpc/lib/request.js:99:15
    at Object.then (/Users/pnedelko/projects/elastic/api/node_modules/when/when.js:355:15)
    at /Users/pnedelko/projects/elastic/api/node_modules/when/when.js:253:12
    at /Users/pnedelko/projects/elastic/api/node_modules/when/when.js:417:5
    at Immediate.drainQueue [as _onImmediate] (/Users/pnedelko/projects/elastic/api/node_modules/when/when.js:735:4)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by tjmehta** [comment]
Interesting, the error indicates that catch is not chain able after then. Current when docs show 'when' is an A+ promise library. I'll have to dig and see what version they are using

**Comment by pnedelko** [comment]
I've tested lib with the latest `amqplib` and it doesn't work as well. As far as I see in code, in `request.js` you doesn't set `corrId` and `replyTo` properties, which is weird. Am I missing something?

**Comment by pnedelko** [comment]
Ah, I see guys are fixing that in this fork https://github.com/Miwwa/amqplib-rpc

**Comment by tjmehta** [comment]
I'm am on the go right now, but will check this out in 2 hours. 

Can you see anything missing in the tests? Anything obvious?

Thanks

Typed using my thumbs..

**Comment by tjmehta** [comment]
You're right I see the problem

**Comment by tjmehta** [comment]
@pnedelko moving to another ticket #7
